### ISSUE TITLE
Video 1.4/end refuses to work

### ISSUE THREAD

**Issue by taserian** [JohnMunsch/Root#1]
I'm not sure what's going wrong, but I've attempted the following in order:
- tried the code changes from the video in the `Video 1.4/start` directory.
- pulled the latest from this github's `final` branch, and modified the `start/index.html` and `start/app/app.component.ts` files by comparing their contents to the corresponding files from the `Video 1.4/end` directory. 
- attempted to run the contents of the `Video 1.4/end` directory.

Each time, all I've gotten is the "Loading ..." page; no "Hello World!" appears. Each time, I've followed the instructions in the video:
- ran `npm install` in the directory.
- made modifications as mentioned above.
- ran `gulp` to serve these files locally.

Running it in `end` won't even transpile the `app.components.ts` into the corresponding `*.js` files. I was able to get TypeScript to transpile it in the `start` directory, but I'm unsure as to how this happened. I think it might have been my editing `gulpfile.js` line 16, which I changed to:

`typescriptSource: [ './app/*.ts' ],`

where it used to be `typescriptSource: [ './app/**/*.ts' ],`. The dir structure made that stand out as an issue, though I'm not sure if that will cause further problems.

Would you have any input as to what else might be wrong? I'll continue with the videos, and hope that this isn't too vital, though the excitement of not getting this simple app to run quickly has mellowed my enthusiasm.

**Comment by JohnMunsch** [comment]
I'm back from vacation so apologies for not getting back to you sooner.

First I need to know if you've had any success with getting anything to run
yet. Second, if not I would like to know what errors you're seeing in the
console within your browser and then I may ask you to try some other things
to see where we can get.

If you've gotten stuck on an example, odds are that others have had
problems too.

John

**Comment by mlotfi2005** [comment]
the same here, when run it, only a blank page load, there is no Hello World!

**Comment by JohnMunsch** [comment]
I just pulled a clean copy of the project into a new directory. I then changed to the Section 1/Video 1.4/end directory and ran "npm install" and then "gulp". A browser opened and I saw "Hello World!". That was for the rc.4 version.

Then I removed the node_modules directory and ran "git checkout final" to switch to the branch running the 2.0 final version of Angular. Again, "npm install" and then "gulp clean". That gave me a chance to confirm the dist directory was destroyed. Then "gulp" and I was again looking at a page in the browser which showed "Hello World!".

I did this with Node.js v6.9.1 installed and NPM v3.10.8 and Chrome as my browser.

I seriously need some more info if I'm going to have any hope of diagnosing why this isn't working for you. "only a blank page load," is not enough information. I need browser used, Node.js version, error messages which appeared in the browser console, etc. Help me out here and I'll do my best to help you.

**Comment by mlotfi2005** [comment]
node -v   gives v4.6.1
npm -v gives 3.10.7
browser : chrome

there is no error when starting gulp .

**Comment by JohnMunsch** [comment]
@mlotfi2005 No surprises there.

OK, more important than anything are any errors from the browser itself. If you bring up the Developer Tools in Chrome, you should see a console. That will have some error messages explaining why it couldn't run the JavaScript to get us "Hello World!"

Please grab that info and hopefully I can get you going.

**Comment by mlotfi2005** [comment]
Thanks for your time, I have already checked the console, there is no error, but the body is empty.

I noticed that in  \Section 1\Video 1.4\start\app   they are 3 files (js, ts, js.map)

but in \Section 1\Video 1.4\end\app there is only one file (ts).

**HI JohnMuncsh, are you there ? I would like to know what was wrong, if there is no solution, I will go and buy another book or video.**
Thanks.

**Comment by JohnMunsch** [comment]
@mlotfi2005 Could you delete the node_modules directory out of the end directory and then zip up the entire directory (as is) and send it to me at john.munsch@gmail.com? Without a browser console error or something to work with, it's difficult for me to know what's going wrong. If you can send me everything in that directory though I should be able to figure out something.

**Comment by mlotfi2005** [comment]
Hi,
Here is an attachment.
Thanks,

**Comment by JohnMunsch** [comment]
@mlotfi2005 I don't see any attachment. If you replied directly to the Github email, it stripped your attachment when you sent your reply. Please send it directly to me or go to Github and drag and drop the file into your reply.

**Comment by mlotfi2005** [comment]
[start.zip](https://github.com/JohnMunsch/Root/files/592185/start.zip)

**Comment by JohnMunsch** [comment]
Thank you very much. Let me see what I can figure out.

**Comment by JohnMunsch** [comment]
@mlotfi2005 

Your code isn't going to work, nor do anything because you never load any of the parts of Angular 2 or SystemJS which must be loaded in the index.html.

If you look at your index.html it looks like this:

```
<!doctype html>
  <head>
    <title>Building Your First Component</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="styles.css">
  </head>
  <body>
    <app></app>


  </body>
</html>

```

All of the bits of JavaScript which do the initialization of the code to start the app are missing from that file. Let's look at the corresponding code from index.html in the end version of Video 1.4:

```
<!doctype html>
  <head>
    <title>Building Your First Component</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="styles.css">
  </head>
  <body>
    <app>Loading...</app>

    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <!-- 2. Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function (err) {
        console.error(err);
      });
    </script>
  </body>
</html>
```

After fixing that problem (and running "npm install" of course) your code worked just fine.
